Repository arcus/education_modules, pull requests merged in 2023-08, with the labels that each got.

#459 Python basics functions methods variables
  python_basics_variables_functions_methods/python_basics_variables_functions_methods.md
  python_basics_writing_python_code/python_basics_writing_python_code.md
Labels: Quality Assurance, Before Wave 2 :fire:

#441 Intro to nhst
  intro_to_nhst/intro_to_nhst.md
Labels: Quality Assurance

#467 Changed title and minor front matter update
  python_basics_variables_functions_methods/python_basics_variables_functions_methods.md
Labels: Before Wave 2 :fire:

#404 Demystifying large language models
  demystifying_large_language_models/demystifying_large_language_models.md
  demystifying_large_language_models/media/example_nn.png
  demystifying_large_language_models/media/example_nn.svg
  demystifying_large_language_models/media/vectors.png
Labels: Quality Assurance

#472 Add instructions for installing packages
  data_visualization_in_seaborn/data_visualization_in_seaborn.md
Labels: Data Visualization in seaborn
